// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/auth/runtime": {
    params: {};
  };
  "/api/billing/checkout": {
    params: {};
  };
  "/api/billing/portal": {
    params: {};
  };
  "/api/billing/runtime": {
    params: {};
  };
  "/api/billing/state": {
    params: {};
  };
  "/api/billing/sync": {
    params: {};
  };
  "/api/billing/webhook": {
    params: {};
  };
  "/api/check-email": {
    params: {};
  };
  "/api/email/runtime": {
    params: {};
  };
  "/api/providers/runtime": {
    params: {};
  };
  "/api/register": {
    params: {};
  };
  "/api/auth/methods": {
    params: {};
  };
  "/api/sms/runtime": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/api/storage/delete": {
    params: {};
  };
  "/api/storage/runtime": {
    params: {};
  };
  "/api/storage/signed-url": {
    params: {};
  };
  "/api/storage/upload": {
    params: {};
  };
  "/api/settings/providers": {
    params: {};
  };
  "/settings/providers": {
    params: {};
  };
  "/uploads/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/auth/runtime" | "/api/billing/checkout" | "/api/billing/portal" | "/api/billing/runtime" | "/api/billing/state" | "/api/billing/sync" | "/api/billing/webhook" | "/api/check-email" | "/api/email/runtime" | "/api/providers/runtime" | "/api/register" | "/api/auth/methods" | "/api/sms/runtime" | "/api/auth/*" | "/api/storage/delete" | "/api/storage/runtime" | "/api/storage/signed-url" | "/api/storage/upload" | "/api/settings/providers" | "/settings/providers" | "/uploads/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/api.auth.runtime.tsx": {
    id: "routes/api.auth.runtime";
    page: "/api/auth/runtime";
  };
  "routes/api.billing.checkout.tsx": {
    id: "routes/api.billing.checkout";
    page: "/api/billing/checkout";
  };
  "routes/api.billing.portal.tsx": {
    id: "routes/api.billing.portal";
    page: "/api/billing/portal";
  };
  "routes/api.billing.runtime.tsx": {
    id: "routes/api.billing.runtime";
    page: "/api/billing/runtime";
  };
  "routes/api.billing.state.tsx": {
    id: "routes/api.billing.state";
    page: "/api/billing/state";
  };
  "routes/api.billing.sync.tsx": {
    id: "routes/api.billing.sync";
    page: "/api/billing/sync";
  };
  "routes/api.billing.webhook.tsx": {
    id: "routes/api.billing.webhook";
    page: "/api/billing/webhook";
  };
  "routes/api.check-email.ts": {
    id: "routes/api.check-email";
    page: "/api/check-email";
  };
  "routes/api.email.runtime.tsx": {
    id: "routes/api.email.runtime";
    page: "/api/email/runtime";
  };
  "routes/api.providers.runtime.tsx": {
    id: "routes/api.providers.runtime";
    page: "/api/providers/runtime";
  };
  "routes/api.register.ts": {
    id: "routes/api.register";
    page: "/api/register";
  };
  "routes/api.auth.methods.tsx": {
    id: "routes/api.auth.methods";
    page: "/api/auth/methods";
  };
  "routes/api.sms.runtime.tsx": {
    id: "routes/api.sms.runtime";
    page: "/api/sms/runtime";
  };
  "routes/api.auth.$.tsx": {
    id: "routes/api.auth.$";
    page: "/api/auth/*";
  };
  "routes/api.storage.delete.tsx": {
    id: "routes/api.storage.delete";
    page: "/api/storage/delete";
  };
  "routes/api.storage.runtime.tsx": {
    id: "routes/api.storage.runtime";
    page: "/api/storage/runtime";
  };
  "routes/api.storage.signed-url.tsx": {
    id: "routes/api.storage.signed-url";
    page: "/api/storage/signed-url";
  };
  "routes/api.storage.upload.tsx": {
    id: "routes/api.storage.upload";
    page: "/api/storage/upload";
  };
  "routes/api.settings.providers.tsx": {
    id: "routes/api.settings.providers";
    page: "/api/settings/providers";
  };
  "routes/settings.providers.tsx": {
    id: "routes/settings.providers";
    page: "/settings/providers";
  };
  "routes/uploads.$.tsx": {
    id: "routes/uploads.$";
    page: "/uploads/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/api.auth.runtime": typeof import("./app/routes/api.auth.runtime.tsx");
  "routes/api.billing.checkout": typeof import("./app/routes/api.billing.checkout.tsx");
  "routes/api.billing.portal": typeof import("./app/routes/api.billing.portal.tsx");
  "routes/api.billing.runtime": typeof import("./app/routes/api.billing.runtime.tsx");
  "routes/api.billing.state": typeof import("./app/routes/api.billing.state.tsx");
  "routes/api.billing.sync": typeof import("./app/routes/api.billing.sync.tsx");
  "routes/api.billing.webhook": typeof import("./app/routes/api.billing.webhook.tsx");
  "routes/api.check-email": typeof import("./app/routes/api.check-email.ts");
  "routes/api.email.runtime": typeof import("./app/routes/api.email.runtime.tsx");
  "routes/api.providers.runtime": typeof import("./app/routes/api.providers.runtime.tsx");
  "routes/api.register": typeof import("./app/routes/api.register.ts");
  "routes/api.auth.methods": typeof import("./app/routes/api.auth.methods.tsx");
  "routes/api.sms.runtime": typeof import("./app/routes/api.sms.runtime.tsx");
  "routes/api.auth.$": typeof import("./app/routes/api.auth.$.tsx");
  "routes/api.storage.delete": typeof import("./app/routes/api.storage.delete.tsx");
  "routes/api.storage.runtime": typeof import("./app/routes/api.storage.runtime.tsx");
  "routes/api.storage.signed-url": typeof import("./app/routes/api.storage.signed-url.tsx");
  "routes/api.storage.upload": typeof import("./app/routes/api.storage.upload.tsx");
  "routes/api.settings.providers": typeof import("./app/routes/api.settings.providers.tsx");
  "routes/settings.providers": typeof import("./app/routes/settings.providers.tsx");
  "routes/uploads.$": typeof import("./app/routes/uploads.$.tsx");
};